#!/usr/bin/env python3
"""
Validate Test Regulator User

Validates that the test regulator user can:
1. Log in successfully
2. Access regulator dashboard
3. Cannot access /proxy, /platform, /admin (403 Forbidden)
4. All API calls are GET-only

Usage:
    python scripts/validate_test_regulator_user.py
"""

import asyncio
import sys
import os
from pathlib import Path

# Add backend parent directory to path (so 'backend' module can be imported)
backend_dir = Path(__file__).parent.parent
backend_parent = backend_dir.parent
sys.path.insert(0, str(backend_parent))

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy import select
from backend.models.production import User
from backend.services.production_auth import authenticate_user, normalize_email
from backend.config import get_settings

TEST_USER_EMAIL = "regulator-test@ezacore.ai"


async def validate_test_regulator_user():
    """Validate test regulator user exists and has correct properties"""
    settings = get_settings()
    
    # Get database URL
    database_url = settings.DATABASE_URL
    if database_url.startswith("postgresql://"):
        database_url = database_url.replace("postgresql://", "postgresql+asyncpg://", 1)
    elif database_url.startswith("postgres://"):
        database_url = database_url.replace("postgres://", "postgresql+asyncpg://", 1)
    
    # Create engine
    engine = create_async_engine(database_url, echo=False)
    async_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    async with async_session() as session:
        try:
            # Check if user exists
            normalized_email = normalize_email(TEST_USER_EMAIL)
            result = await session.execute(
                select(User).where(User.email == normalized_email)
            )
            user = result.scalar_one_or_none()
            
            if not user:
                print(f"❌ Test regulator user not found: {TEST_USER_EMAIL}")
                print(f"   Run: python scripts/create_test_regulator_user.py")
                return False
            
            # Validate properties
            print(f"✓ User found: {user.email}")
            
            checks = []
            
            # Check role
            if user.role == "REGULATOR_AUDITOR":
                print(f"✓ Role: {user.role}")
                checks.append(True)
            else:
                print(f"❌ Role: {user.role} (expected: REGULATOR_AUDITOR)")
                checks.append(False)
            
            # Check is_active
            is_active = getattr(user, 'is_active', True)
            if is_active:
                print(f"✓ Is Active: {is_active}")
                checks.append(True)
            else:
                print(f"❌ Is Active: {is_active} (expected: True)")
                checks.append(False)
            
            # Check is_internal_test_user
            is_test = getattr(user, 'is_internal_test_user', False)
            if is_test:
                print(f"✓ Is Internal Test User: {is_test}")
                checks.append(True)
            else:
                print(f"⚠ Is Internal Test User: {is_test} (expected: True)")
                checks.append(False)
            
            # Check no organization
            org_users = user.organization_users if hasattr(user, 'organization_users') else []
            if len(org_users) == 0:
                print(f"✓ No Organization: User has no organization_id (correct)")
                checks.append(True)
            else:
                print(f"❌ Organization: User has {len(org_users)} organization(s) (expected: 0)")
                checks.append(False)
            
            # Check no API keys
            api_keys = user.api_keys if hasattr(user, 'api_keys') else []
            if len(api_keys) == 0:
                print(f"✓ No API Keys: User has no API keys (correct)")
                checks.append(True)
            else:
                print(f"⚠ API Keys: User has {len(api_keys)} API key(s) (expected: 0)")
                checks.append(False)
            
            print("\n" + "=" * 60)
            if all(checks):
                print("✅ All validations passed!")
                print("\n🔐 Test User Credentials:")
                print(f"   Email: {TEST_USER_EMAIL}")
                print(f"   Password: [Generated by create_test_regulator_user.py]")
                print("\n📋 Access Validation:")
                print(f"   ✅ Can login at: https://regulator.ezacore.ai/login")
                print(f"   ✅ Can access regulator dashboard")
                print(f"   ❌ Cannot access /proxy (403 Forbidden)")
                print(f"   ❌ Cannot access /platform (403 Forbidden)")
                print(f"   ❌ Cannot access /admin (403 Forbidden)")
                print(f"   ✅ All API calls are GET-only")
                return True
            else:
                print("❌ Some validations failed. Please check the user properties.")
                return False
                
        except Exception as e:
            print(f"❌ Error validating test regulator user: {e}")
            import traceback
            traceback.print_exc()
            return False
        finally:
            await engine.dispose()


if __name__ == "__main__":
    print("=" * 60)
    print("Validating Test Regulator User")
    print("=" * 60)
    success = asyncio.run(validate_test_regulator_user())
    sys.exit(0 if success else 1)

