# -*- coding: utf-8 -*-
"""Stable operational error codes (safe for logs / optional UI reference)."""

from __future__ import annotations

# Auth
AUTH_SESSION_INVALID = "AUTH_SESSION_INVALID"
AUTH_PROVIDER_FAILED = "AUTH_PROVIDER_FAILED"
AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
AUTH_REGISTER_FAILED = "AUTH_REGISTER_FAILED"
SOCIAL_AUTH_FAILED = "SOCIAL_AUTH_FAILED"
ACCOUNT_LINK_REQUIRED = "ACCOUNT_LINK_REQUIRED"

# Discover / public surface
DISCOVER_LOAD_FAILED = "DISCOVER_LOAD_FAILED"
YANSI_NOT_AVAILABLE = "YANSI_NOT_AVAILABLE"
FROZEN_ARTIFACT_INVALID = "FROZEN_ARTIFACT_INVALID"
SHARE_ROUTE_LOAD_FAILED = "SHARE_ROUTE_LOAD_FAILED"

# Sohbet / continuation
SOHBET_SESSION_FAILED = "SOHBET_SESSION_FAILED"
GUEST_CLAIM_FAILED = "GUEST_CLAIM_FAILED"
JOURNEY_REBIND_FAILED = "JOURNEY_REBIND_FAILED"

# Ayna / scene
AYNA_PREPARE_FAILED = "AYNA_PREPARE_FAILED"
AYNA_SCENE_FAILED = "AYNA_SCENE_FAILED"
AYNA_GENERATION_FAILED = "AYNA_GENERATION_FAILED"

# Publish
PUBLISH_FAILED = "PUBLISH_FAILED"
PUBLISH_RECOVERY_FAILED = "PUBLISH_RECOVERY_FAILED"

# Provider
PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
PROVIDER_UPSTREAM_ERROR = "PROVIDER_UPSTREAM_ERROR"
PROVIDER_REQUEST_FAILED = "PROVIDER_REQUEST_FAILED"

# Generic system
INTERNAL_ERROR = "INTERNAL_ERROR"

# Expected product states (not incidents)
EXPECTED_NOT_FOUND = "EXPECTED_NOT_FOUND"
EXPECTED_AUTH_REQUIRED = "EXPECTED_AUTH_REQUIRED"
EXPECTED_USER_CANCEL = "EXPECTED_USER_CANCEL"
EXPECTED_QUOTA = "EXPECTED_QUOTA"
EXPECTED_WITHDRAWN = "EXPECTED_WITHDRAWN"

EXPECTED_CODES = frozenset(
    {
        EXPECTED_NOT_FOUND,
        EXPECTED_AUTH_REQUIRED,
        EXPECTED_USER_CANCEL,
        EXPECTED_QUOTA,
        EXPECTED_WITHDRAWN,
        ACCOUNT_LINK_REQUIRED,
        YANSI_NOT_AVAILABLE,
        FROZEN_ARTIFACT_INVALID,
    }
)
