# -*- coding: utf-8 -*-
"""
Telemetry Event Pydantic Schemas
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime
from uuid import UUID


class TelemetryEventBase(BaseModel):
    """Base telemetry event schema"""
    model_config = ConfigDict(protected_namespaces=())
    
    mode: str = Field(..., description="Pipeline mode: standalone, proxy, or proxy-lite")
    source: str = Field(..., description="Event source: standalone-api, proxy-api, etc.")
    user_input: str = Field(..., description="User input text")
    safe_answer: Optional[str] = Field(None, description="Safe answer generated by pipeline")
    eza_score: Optional[float] = Field(None, description="EZA Score v2.1 (0-100)")
    risk_level: Optional[str] = Field(None, description="Risk level: low, medium, high")
    policy_violations: Optional[List[str]] = Field(None, description="List of policy violations")
    model_votes: Optional[Dict[str, Any]] = Field(None, description="Model/provider usage information")
    meta: Optional[Dict[str, Any]] = Field(None, description="Additional metadata")


class TelemetryEventCreate(TelemetryEventBase):
    """Schema for creating a telemetry event"""
    pass


class TelemetryEventRead(TelemetryEventBase):
    """Schema for reading a telemetry event"""
    id: UUID = Field(..., description="Event UUID")
    timestamp: datetime = Field(..., description="Event timestamp")
    
    class Config:
        from_attributes = True


class TelemetryListResponse(BaseModel):
    """Response schema for telemetry event lists"""
    items: List[TelemetryEventRead] = Field(..., description="List of telemetry events")
    total: int = Field(..., description="Total number of events")
    newest_timestamp: Optional[datetime] = Field(None, description="Timestamp of newest event")

